FROM hexpm/elixir:1.20.2-erlang-29.0.3-debian-trixie-20260713-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends git ca-certificates nodejs npm && \
    rm -rf /var/lib/apt/lists/*
