defmodule Aprs.CompressedPositionHelpersTest do
  use ExUnit.Case, async: true
  use ExUnitProperties

  describe "convert_compressed_lat/1" do
    property "converts valid 4-byte compressed latitude" do
      check all lat_bytes <- StreamData.binary(length: 4) do
        # Clamp generated bytes to the APRS base-91 range.
        valid_bytes = for <<byte <- lat_bytes>>, do: max(33, min(123, byte))
        valid_lat = :binary.list_to_bin(valid_bytes)

        case Aprs.CompressedPositionHelpers.convert_compressed_lat(valid_lat) do
          {:ok, lat} ->
            assert is_float(lat)
            assert lat >= -90.0 and lat <= 90.0

          {:error, _} ->
            :ok
        end
      end
    end

    test "converts known values and rejects out-of-range coordinates" do
      assert {:ok, 90.0} = Aprs.CompressedPositionHelpers.convert_compressed_lat("!!!!")

      assert {:error, "Invalid compressed latitude - out of range"} =
               Aprs.CompressedPositionHelpers.convert_compressed_lat("{{{{")
    end

    test "returns error for invalid input" do
      assert {:error, "Invalid compressed latitude"} = Aprs.CompressedPositionHelpers.convert_compressed_lat("")
      assert {:error, "Invalid compressed latitude"} = Aprs.CompressedPositionHelpers.convert_compressed_lat("123")
      assert {:error, "Invalid compressed latitude"} = Aprs.CompressedPositionHelpers.convert_compressed_lat("12345")
      assert {:error, "Invalid compressed latitude"} = Aprs.CompressedPositionHelpers.convert_compressed_lat(nil)

      assert {:error, "Invalid compressed latitude - contains non-ASCII characters"} =
               Aprs.CompressedPositionHelpers.convert_compressed_lat("~~~~")

      assert {:error, "Invalid compressed latitude - invalid encoding"} =
               Aprs.CompressedPositionHelpers.convert_compressed_lat(<<255, 255, 255, 255>>)
    end

    test "handles edge cases" do
      # Test with various byte combinations
      assert {:ok, _} = Aprs.CompressedPositionHelpers.convert_compressed_lat("ABCD")
      assert {:ok, _} = Aprs.CompressedPositionHelpers.convert_compressed_lat("1234")
      assert {:ok, _} = Aprs.CompressedPositionHelpers.convert_compressed_lat("!@#$")
    end
  end

  describe "convert_compressed_lon/1" do
    property "converts valid 4-byte compressed longitude" do
      check all lon_bytes <- StreamData.binary(length: 4) do
        # Clamp generated bytes to the APRS base-91 range.
        valid_bytes = for <<byte <- lon_bytes>>, do: max(33, min(123, byte))
        valid_lon = :binary.list_to_bin(valid_bytes)

        case Aprs.CompressedPositionHelpers.convert_compressed_lon(valid_lon) do
          {:ok, lon} ->
            assert is_float(lon)
            assert lon >= -180.0 and lon <= 180.0

          {:error, _} ->
            :ok
        end
      end
    end

    test "converts known values and rejects out-of-range coordinates" do
      assert {:ok, -180.0} = Aprs.CompressedPositionHelpers.convert_compressed_lon("!!!!")

      assert {:error, "Invalid compressed longitude - out of range"} =
               Aprs.CompressedPositionHelpers.convert_compressed_lon("{{{{")
    end

    test "returns error for invalid input" do
      assert {:error, "Invalid compressed longitude"} = Aprs.CompressedPositionHelpers.convert_compressed_lon("")
      assert {:error, "Invalid compressed longitude"} = Aprs.CompressedPositionHelpers.convert_compressed_lon("123")
      assert {:error, "Invalid compressed longitude"} = Aprs.CompressedPositionHelpers.convert_compressed_lon("12345")
      assert {:error, "Invalid compressed longitude"} = Aprs.CompressedPositionHelpers.convert_compressed_lon(nil)

      assert {:error, "Invalid compressed longitude - contains non-ASCII characters"} =
               Aprs.CompressedPositionHelpers.convert_compressed_lon("~~~~")

      assert {:error, "Invalid compressed longitude - invalid encoding"} =
               Aprs.CompressedPositionHelpers.convert_compressed_lon(<<255, 255, 255, 255>>)
    end

    test "handles edge cases" do
      # Test with various byte combinations
      assert {:ok, _} = Aprs.CompressedPositionHelpers.convert_compressed_lon("ABCD")
      assert {:ok, _} = Aprs.CompressedPositionHelpers.convert_compressed_lon("1234")
      assert {:ok, _} = Aprs.CompressedPositionHelpers.convert_compressed_lon("!@#$")
    end
  end

  describe "parse_compression_type/1" do
    test "decodes the compression type bit fields" do
      assert Aprs.CompressedPositionHelpers.parse_compression_type("T") == %{
               gps_fix: :current,
               nmea_source: :gga,
               origin: :tbd
             }

      assert Aprs.CompressedPositionHelpers.parse_compression_type("I") == %{
               gps_fix: :current,
               nmea_source: :gll,
               origin: :compressed
             }

      assert Aprs.CompressedPositionHelpers.parse_compression_type("Y") == %{
               gps_fix: :current,
               nmea_source: :rmc,
               origin: :compressed
             }
    end

    test "decodes all origin values" do
      origins = [
        :compressed,
        :tnc_btext,
        :software,
        :tbd,
        :kpc3,
        :pico,
        :other_tracker,
        :digipeater_conversion
      ]

      for {origin, offset} <- Enum.with_index(origins) do
        type = <<33 + offset>>

        assert Aprs.CompressedPositionHelpers.parse_compression_type(type) == %{
                 gps_fix: :old,
                 nmea_source: :other,
                 origin: origin
               }
      end
    end

    test "uses the value-zero map for empty and below-offset bytes" do
      expected = %{gps_fix: :old, nmea_source: :other, origin: :compressed}

      assert Aprs.CompressedPositionHelpers.parse_compression_type("") == expected
      assert Aprs.CompressedPositionHelpers.parse_compression_type(" ") == expected
    end
  end

  describe "convert_to_base91/1" do
    property "converts 4-byte strings to base91 integers" do
      check all bytes <- StreamData.binary(length: 4) do
        # Clamp generated bytes to the APRS base-91 range.
        valid_bytes = for <<byte <- bytes>>, do: max(33, min(123, byte))
        valid_string = :binary.list_to_bin(valid_bytes)

        result = Aprs.CompressedPositionHelpers.convert_to_base91(valid_string)
        assert is_integer(result)
        assert result >= 0
      end
    end

    test "converts known values correctly" do
      assert Aprs.CompressedPositionHelpers.convert_to_base91("!!!!") == 0
      assert Aprs.CompressedPositionHelpers.convert_to_base91("ABCD") == 24_390_674
      assert Aprs.CompressedPositionHelpers.convert_to_base91("~~~~") == 70_860_792
    end

    test "handles edge cases" do
      assert Aprs.CompressedPositionHelpers.convert_to_base91("~~~~") > 0
      assert Aprs.CompressedPositionHelpers.convert_to_base91("1234") > 0
      assert Aprs.CompressedPositionHelpers.convert_to_base91("!@#$") > 0
    end

    test "raises error for invalid input" do
      # The implementation may not raise, so check for error tuple
      assert_raise FunctionClauseError, fn ->
        Aprs.CompressedPositionHelpers.convert_to_base91("")
      end

      assert_raise FunctionClauseError, fn ->
        Aprs.CompressedPositionHelpers.convert_to_base91("123")
      end

      assert_raise FunctionClauseError, fn ->
        Aprs.CompressedPositionHelpers.convert_to_base91("12345")
      end
    end
  end

  describe "convert_compressed_cs/1 and convert_compressed_cs/2" do
    property "decodes every valid course/speed pair to a map" do
      check all cs_bytes <- StreamData.binary(length: 2) do
        valid_bytes = for <<byte <- cs_bytes>>, do: max(33, min(123, byte))
        valid_cs = :binary.list_to_bin(valid_bytes)

        assert is_map(Aprs.CompressedPositionHelpers.convert_compressed_cs(valid_cs, " "))
      end
    end

    test "decodes the APRS101 worked course and speed example in knots" do
      result = Aprs.CompressedPositionHelpers.convert_compressed_cs("7P", " ")

      assert result.course == 88
      assert_in_delta result.speed, 1.08 ** 47 - 1, 1.0e-12
      assert_in_delta result.speed, 36.2, 0.1
    end

    test "uses 360 for due north and permits zero speed" do
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("!!", " ") == %{
               course: 360,
               speed: 0.0
             }
    end

    test "decodes Z as a course byte and ampersand as a valid course byte" do
      assert %{course: 228} = Aprs.CompressedPositionHelpers.convert_compressed_cs("Z7", " ")

      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("&!", " ") == %{
               course: 20,
               speed: 0.0
             }
    end

    test "decodes the radio range marker" do
      result = Aprs.CompressedPositionHelpers.convert_compressed_cs("{?", " ")

      assert_in_delta result.range, 2 * 1.08 ** 30, 1.0e-12
      assert_in_delta result.range, 20.0, 0.2
      refute Map.has_key?(result, :course)
      refute Map.has_key?(result, :speed)
    end

    test "decodes cs as altitude for a GGA compression type" do
      result = Aprs.CompressedPositionHelpers.convert_compressed_cs("S]", "1")

      assert_in_delta result.altitude, 1.002 ** 4610, 1.0e-9
      refute Map.has_key?(result, :course)
      refute Map.has_key?(result, :speed)
    end

    test "one-arity form uses the value-zero compression type" do
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("7P") ==
               Aprs.CompressedPositionHelpers.convert_compressed_cs("7P", " ")
    end

    test "an empty compression type is not a GGA type, so cs stays course and speed" do
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("7P", "") ==
               Aprs.CompressedPositionHelpers.convert_compressed_cs("7P", " ")
    end

    test "returns an empty map when cs is absent or invalid" do
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("  ", " ") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs(<<32, 33>>, " ") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs(<<33, 32>>, " ") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("  ", "1") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs(<<32, 33>>, "1") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs(<<33, 32>>, "1") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("~!", " ") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs(nil, " ") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("", " ") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("A", " ") == %{}
      assert Aprs.CompressedPositionHelpers.convert_compressed_cs("ABC", " ") == %{}
    end
  end

  describe "integration tests" do
    test "converts complete compressed position" do
      # Test a complete compressed position conversion
      lat_result = Aprs.CompressedPositionHelpers.convert_compressed_lat("ABCD")
      lon_result = Aprs.CompressedPositionHelpers.convert_compressed_lon("EFGH")
      cs_result = Aprs.CompressedPositionHelpers.convert_compressed_cs("IJ")

      assert {:ok, lat} = lat_result
      assert {:ok, lon} = lon_result
      assert is_map(cs_result)

      assert is_float(lat)
      assert is_float(lon)
      assert lat >= -90.0 and lat <= 90.0
      assert lon >= -180.0 and lon <= 180.0
    end

    test "handles real-world compressed position example" do
      # Example from APRS specification
      lat_result = Aprs.CompressedPositionHelpers.convert_compressed_lat("L9f\\")
      lon_result = Aprs.CompressedPositionHelpers.convert_compressed_lon("]UP1")

      assert {:ok, lat} = lat_result
      assert {:ok, lon} = lon_result

      # Should be in reasonable range for the example
      assert lat > 0 and lat < 90
      assert lon > 0 and lon < 180
    end
  end
end
